export const DEFAULT_LANG = 'en-US';
export const BASE_URL = process.env.NODE_ENV === "development" ? '' : '/vtg/';
export const RESOURCES_PATH = BASE_URL + 'resources/';
export const TOKEN_KEY = 'token';
export const REFRESH_TOKEN_KEY = 'rfToken';
export const LOGIN_KEY = 'loggedin';
export const LOGOUT_KEY = 'loggedout';
export const TOKEN_EXPIRED_TIME = 1 / 48;
export const TOKEN_COOKIE_PATH = 'provider';
export const AUTO_LOGOUT_TIME = 3600;